const byId = (id) => document.getElementById(id);

export function getElements() {
  return {
    screens: [...document.querySelectorAll(".screen")],
    homeLogo: byId("homeLogo"),
    crumb: byId("crumb"),
    themeToggle: byId("themeToggle"),
    themeToggleLabel: byId("themeToggleLabel"),
    sessionEstimate: byId("sessionEstimate"),
    streakDots: byId("streakDots"),
    streakLabel: byId("streakLabel"),
    feedbackTip: byId("feedbackTip"),
    nextStepCard: byId("nextStepCard"),
    nextStepText: byId("nextStepText"),
    navPractice: byId("navPractice"),
    navLibrary: byId("navLibrary"),
    levelGrid: byId("levelGrid"),
    levelTemplate: byId("levelCardTemplate"),
    choiceTemplate: byId("choiceTemplate"),
    reviewTemplate: byId("reviewTemplate"),
    libraryTemplate: byId("libraryCardTemplate"),
    resumePanel: byId("resumePanel"),
    resumeText: byId("resumeText"),
    resumeButton: byId("resumeButton"),
    discardResumeButton: byId("discardResumeButton"),
    saveAndExitButton: byId("saveAndExitButton"),
    questionCounter: byId("questionCounter"),
    progressPercent: byId("progressPercent"),
    quizProgress: byId("quizProgress"),
    answeredCount: byId("answeredCount"),
    correctCount: byId("correctCount"),
    wrongCount: byId("wrongCount"),
    questionLevel: byId("questionLevel"),
    questionTopic: byId("questionTopic"),
    questionPrompt: byId("questionPrompt"),
    choiceList: byId("choiceList"),
    feedbackPanel: byId("feedbackPanel"),
    feedbackTitle: byId("feedbackTitle"),
    feedbackExplanation: byId("feedbackExplanation"),
    feedbackSource: byId("feedbackSource"),
    nextQuestionButton: byId("nextQuestionButton"),
    nextSlot: byId("nextSlot"),
    resultTitle: byId("resultTitle"),
    resultMessage: byId("resultMessage"),
    resultPercent: byId("resultPercent"),
    resultCorrect: byId("resultCorrect"),
    resultWrong: byId("resultWrong"),
    resultTotal: byId("resultTotal"),
    retryWrongButton: byId("retryWrongButton"),
    newSessionButton: byId("newSessionButton"),
    resultHomeButton: byId("resultHomeButton"),
    reviewList: byId("reviewList"),
    reviewMoreButton: byId("reviewMoreButton"),
    librarySearch: byId("librarySearch"),
    libraryLevel: byId("libraryLevel"),
    libraryTopic: byId("libraryTopic"),
    librarySummary: byId("librarySummary"),
    libraryList: byId("libraryList"),
    libraryEmpty: byId("libraryEmpty"),
    libraryMoreButton: byId("libraryMoreButton"),
    libraryDialog: byId("libraryDialog"),
    libraryDialogClose: byId("libraryDialogClose"),
    libraryDialogLevel: byId("libraryDialogLevel"),
    libraryDialogTopic: byId("libraryDialogTopic"),
    libraryDialogPrompt: byId("libraryDialogPrompt"),
    libraryDialogAnswer: byId("libraryDialogAnswer"),
    libraryDialogWrong: byId("libraryDialogWrong"),
    libraryDialogTip: byId("libraryDialogTip"),
    libraryDialogExplanation: byId("libraryDialogExplanation"),
    libraryDialogSource: byId("libraryDialogSource"),
    bankVersion: byId("bankVersion"),
  };
}

export { byId };
